version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=b72865fa-31ec-4ce0-a7fb-518bdef55c2e
      - SPLUNK_PASSWORD
    ports:
      - "8000:8000"
      - "8088:8088"